### ISSUE TITLE
Webhook not working in game

### ISSUE THREAD

**Issue by HAHOOS** [JJBIoxxer/Roblox-Discord-API#1]
Hello, I am using this module and it's working awesome on roblox studio, but there is one problem. When player plays game script don't work

**Comment by JJBIoxxer** [comment]
Discord banned requests coming from Roblox a few months ago which is why this doesn't work in game. I haven't had time to update the module to bypass the ban. If you need it to work right now, your best bet is to use [ProxyService](https://github.com/sentanos/ProxyService). You'll have to use the Message object's "rawdata" property to get the message data and then encode it using the JSONEncode function of HttpService. Sorry for any inconvenience this may have caused you. I'll try and get an updated version of this module released as soon as I can.

**Comment by HAHOOS** [comment]
Thank you for letting me know. I knew that was banned, but didn't know it is not updated.
